import {BadgePercent,CheckCircle2,Loader2,RefreshCcw,XCircle} from 'lucide-react';
import {useEffect,useState} from 'react';
import {commerceClient} from '../api/commerce-client';
import type {CommerceDiscountCode,CommerceDiscountType,CommercePaymentRequest,CommerceProductType} from '../api/commerce-types';
const money=(minor:number,currency:string)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency}).format(minor/100);
export function CommercePaymentsPanel({getCsrfToken}:{getCsrfToken:()=>Promise<string>}){
 const[requests,setRequests]=useState<CommercePaymentRequest[]>([]);const[discounts,setDiscounts]=useState<CommerceDiscountCode[]>([]);
 const[code,setCode]=useState('');const[label,setLabel]=useState('');const[type,setType]=useState<CommerceDiscountType>('percentage');const[value,setValue]=useState(10);const[productType,setProductType]=useState<CommerceProductType|''>('');
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[reload,setReload]=useState(0);
 useEffect(()=>{const c=new AbortController();setBusy(true);Promise.all([commerceClient.paymentRequests(1,50,'',c.signal),commerceClient.discounts(1,50,'','',c.signal)]).then(([p,d])=>{setRequests(p.items);setDiscounts(d.items)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل طلبات الدفع')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[reload]);
 async function createDiscount(){if(!code.trim())return;setBusy(true);setError('');try{const csrf=await getCsrfToken();await commerceClient.createDiscount({code:code.trim().toUpperCase(),label:label.trim(),type,value:Math.max(1,Math.trunc(value)),currency:'SAR',status:'active',productId:'',productType,minAmountMinor:0,maxRedemptions:0,startsAt:null,expiresAt:null},csrf);setCode('');setLabel('');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الخصم')}finally{setBusy(false)}}
 async function toggleDiscount(row:CommerceDiscountCode){setBusy(true);try{const csrf=await getCsrfToken();await commerceClient.updateDiscount(row,{code:row.code,label:row.label,type:row.type,value:row.value,currency:row.currency,status:row.status==='active'?'paused':'active',productId:row.productId,productType:row.productType,minAmountMinor:row.minAmountMinor,maxRedemptions:row.maxRedemptions,startsAt:row.startsAt,expiresAt:row.expiresAt},csrf);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث الخصم')}finally{setBusy(false)}}
 async function review(row:CommercePaymentRequest,status:'approved'|'rejected'){let evidence='';if(status==='approved'){evidence=window.prompt('اكتب دليل الاعتماد/التحقق (6 أحرف على الأقل):','manual review')||'';if(evidence.trim().length<6)return}setBusy(true);try{const csrf=await getCsrfToken();await commerceClient.reviewPaymentRequest(row,status,status==='approved'?'اعتماد يدوي':'رفض الطلب',evidence,csrf);setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر مراجعة الطلب')}finally{setBusy(false)}}
 return <section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl font-black">الدفع والخصومات</h2><button type="button" onClick={()=>setReload(x=>x+1)} className="inline-flex items-center gap-1 text-sm font-black text-indigo-700"><RefreshCcw size={15}/>تحديث</button></div>{error?<div className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}
 <div className="grid gap-4 lg:grid-cols-2"><div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><BadgePercent size={18}/>كود خصم</div><input aria-label="كود الخصم الإداري" value={code} onChange={e=>setCode(e.target.value)} placeholder="SAVE10" className="w-full rounded-xl border p-2.5"/><input aria-label="وصف الخصم" value={label} onChange={e=>setLabel(e.target.value)} placeholder="خصم إطلاق" className="w-full rounded-xl border p-2.5"/><div className="grid grid-cols-2 gap-2"><select aria-label="نوع الخصم" value={type} onChange={e=>setType(e.target.value as CommerceDiscountType)} className="rounded-xl border p-2.5"><option value="percentage">نسبة %</option><option value="fixed">قيمة ثابتة بالهللة</option></select><input aria-label="قيمة الخصم" type="number" min={1} value={value} onChange={e=>setValue(Number(e.target.value)||0)} className="rounded-xl border p-2.5"/></div><select aria-label="نوع المنتج المؤهل" value={productType} onChange={e=>setProductType(e.target.value as CommerceProductType|'')} className="w-full rounded-xl border p-2.5"><option value="">كل المنتجات</option><option value="course">دورة</option><option value="package">باقة</option><option value="membership">عضوية</option></select><button type="button" disabled={busy||!code.trim()} onClick={()=>void createDiscount()} className="rounded-xl bg-indigo-600 px-4 py-2.5 font-black text-white disabled:opacity-40">إنشاء الخصم</button><div className="divide-y rounded-xl border">{discounts.slice(0,8).map(row=><div key={row.id} className="flex items-center justify-between gap-2 p-3 text-sm"><div><div className="font-black">{row.code}</div><div className="text-xs text-gray-500">{row.type==='percentage'?row.value+'%':money(row.value,row.currency)} · {row.currentRedemptions}{row.maxRedemptions>0?'/'+row.maxRedemptions:''}</div></div><button type="button" onClick={()=>void toggleDiscount(row)} className="rounded-lg border px-2 py-1 text-xs font-black">{row.status==='active'?'إيقاف':'تفعيل'}</button></div>)}</div></div>
 <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4 font-black">طلبات الدفع الأخيرة</div>{busy&&requests.length===0?<div className="p-8 text-center"><Loader2 className="mx-auto animate-spin"/></div>:<div className="divide-y">{requests.length===0?<div className="p-6 text-center text-sm font-bold text-gray-500">لا توجد طلبات.</div>:requests.map(row=><article key={row.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><div className="font-black">{row.productName}</div><div className="mt-1 text-xs font-bold text-gray-500">{row.userId} · {row.paymentMethod} · {row.status}</div></div><div className="font-black">{money(row.finalAmountMinor,row.currency)}</div></div>{row.status==='pending'?<div className="mt-3 flex gap-2"><button type="button" disabled={busy} onClick={()=>void review(row,'approved')} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-black text-white"><CheckCircle2 size={14}/>اعتماد</button><button type="button" disabled={busy} onClick={()=>void review(row,'rejected')} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-700"><XCircle size={14}/>رفض</button></div>:null}</article>)}</div>}</div></div></section>;
}
