import{Maximize2,Radio,Users}from'lucide-react';
import{useCallback,useEffect,useRef,useState}from'react';
import{useParams}from'react-router-dom';
import{classroomClient}from'../api/classroom-client';
import type{ClassroomPresentation}from'../api/classroom-types';

export function ClassroomProjectorPage(){
 const{sessionId=''}=useParams();const[presentation,setPresentation]=useState<ClassroomPresentation|null>(null);const[error,setError]=useState('');const socketRef=useRef<WebSocket|null>(null);const pin=sessionId?sessionStorage.getItem('almeaa:classroom:pin:'+sessionId)||'':'';
 const refresh=useCallback(async()=>{if(!sessionId)return;try{const out=await classroomClient.presentation(sessionId);setPresentation(out.presentation);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل شاشة العرض')}},[sessionId]);
 useEffect(()=>{void refresh()},[refresh]);
 useEffect(()=>{if(!sessionId)return;let stopped=false;let retry:number|undefined;const connect=()=>{if(stopped)return;try{const ws=classroomClient.websocket(sessionId);socketRef.current=ws;ws.onmessage=()=>void refresh();ws.onclose=()=>{if(!stopped)retry=window.setTimeout(connect,1500)};ws.onerror=()=>ws.close()}catch{retry=window.setTimeout(connect,2000)}};connect();const poll=window.setInterval(()=>void refresh(),5000);return()=>{stopped=true;if(retry)window.clearTimeout(retry);window.clearInterval(poll);socketRef.current?.close()}},[sessionId,refresh]);
 const active=presentation?.questions.find(q=>q.ordinal===presentation.activeQuestionOrdinal)||presentation?.questions[0]||null;const agg=presentation?.aggregate.questions.find(q=>q.ordinal===active?.ordinal);
 return <main dir="rtl" className="min-h-screen bg-slate-950 p-4 text-white sm:p-8"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-col gap-4 rounded-3xl border border-white/10 bg-white/5 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-cyan-300"><Radio size={18}/><span className="text-xs font-black">PROJECTOR MODE</span></div><h1 className="mt-2 text-3xl font-black">الفصل الذكي</h1></div><div className="flex items-center gap-3"><div className="rounded-2xl bg-white/10 px-4 py-3 text-center"><div className="flex items-center justify-center gap-2 text-xs font-bold text-slate-300"><Users size={14}/>الحضور</div><div className="mt-1 text-2xl font-black">{presentation?.aggregate.joinedCount||0}</div></div>{pin?<div className="rounded-2xl bg-cyan-400 px-5 py-3 text-center text-slate-950"><div className="text-[10px] font-black">PIN</div><div dir="ltr" className="text-2xl font-black tracking-[.2em]">{pin}</div></div>:null}<button type="button" aria-label="ملء الشاشة" onClick={()=>void document.documentElement.requestFullscreen?.()} className="inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-white/15"><Maximize2/></button></div></header>{error?<div role="alert" className="rounded-xl bg-rose-500/20 p-3 font-bold text-rose-200">{error}</div>:null}{active?<section className="rounded-[2rem] bg-white p-6 text-slate-950 shadow-2xl sm:p-10"><div className="text-sm font-black text-indigo-600">السؤال #{active.ordinal+1}</div><h2 className="mt-4 text-3xl font-black leading-[1.7] sm:text-5xl">{active.text||'سؤال بصري'}</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{active.options.map(o=><div key={o.index} className={`rounded-3xl border-2 p-5 text-xl font-black ${active.revealed&&active.correctOptionIndex===o.index?'border-emerald-500 bg-emerald-50':'border-slate-100'}`}><div className="flex items-center justify-between gap-4"><span>{o.index+1}. {o.text||'خيار'}</span><span className="rounded-full bg-slate-100 px-4 py-2 text-base">{agg?.distribution[String(o.index)]||0}</span></div></div>)}</div>{active.revealed&&active.explanation?<div className="mt-8 rounded-3xl bg-emerald-50 p-5 text-xl font-bold leading-9 text-emerald-800">{active.explanation}</div>:null}</section>:<section className="rounded-[2rem] border border-white/10 bg-white/5 p-16 text-center"><Radio className="mx-auto text-slate-600" size={60}/><h2 className="mt-5 text-3xl font-black">بانتظار نشر السؤال</h2><p className="mt-2 text-slate-400">رمز الانضمام يبقى في شاشة المعلم عند إنشاء الحصة.</p></section>}<div className="text-center text-xs font-bold text-slate-500">رابط الانضمام المباشر: {window.location.origin}/classroom/{sessionId}</div></div></main>;
}
