import{Building2,Loader2,Save,ShieldCheck}from'lucide-react';
import{useEffect,useState}from'react';
import{useAuth}from'../../auth/state/AuthProvider';
import{organizationsClient,type SchoolSummary}from'../../organizations/api/organizations-client';
import{classroomClient}from'../api/classroom-client';
import type{SchoolContract}from'../api/classroom-types';

const baseModules=['SCHOOL_CORE','SMART_CLASSROOM'];
export function ClassroomContractsAdminPage(){
 const{user,loading,getCsrfToken}=useAuth();const[schools,setSchools]=useState<SchoolSummary[]>([]);const[selected,setSelected]=useState('');const[contract,setContract]=useState<SchoolContract|null>(null);const[enabled,setEnabled]=useState(true);const[busy,setBusy]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
 useEffect(()=>{if(loading||!user?.roles.includes('admin'))return;organizationsClient.schools().then(x=>{setSchools(x.schools);if(x.schools[0])setSelected(x.schools[0].id)}).catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل المدارس')).finally(()=>setBusy(false))},[loading,user]);
 useEffect(()=>{if(!selected)return;setContract(null);setEnabled(true);classroomClient.contract(selected).then(x=>{setContract(x.contract);setEnabled(x.contract.status==='active'&&x.contract.modules.includes('SMART_CLASSROOM'))}).catch(()=>{setContract(null);setEnabled(false)})},[selected]);
 async function save(){if(!selected)return;setSaving(true);setError('');setNotice('');try{const csrf=await getCsrfToken();const modules=enabled?baseModules:['SCHOOL_CORE'];const out=await classroomClient.saveContract(selected,{status:'active',modules,validFrom:null,validUntil:null,expectedRevision:contract?.revision||0},csrf);setContract(out.contract);setNotice(enabled?'تم تفعيل Smart Classroom بعقد المدرسة.':'تم تعطيل Smart Classroom مع الاحتفاظ بـ SCHOOL_CORE.')}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ عقد المدرسة')}finally{setSaving(false)}}
 if(loading||busy)return <main dir="rtl" className="p-10 text-center font-black"><Loader2 className="mx-auto animate-spin"/>جاري التحميل...</main>;
 if(!user?.roles.includes('admin'))return <main dir="rtl" className="p-10 text-center font-black text-rose-700">هذه الشاشة لمدير المنصة فقط.</main>;
 return <main dir="rtl" className="mx-auto max-w-5xl space-y-5"><header className="rounded-3xl bg-slate-950 p-6 text-white"><div className="flex items-center gap-2 text-cyan-300"><ShieldCheck size={18}/><span className="text-xs font-black">SCHOOL CONTRACT MODULE</span></div><h1 className="mt-2 text-2xl font-black">تفعيل الفصل الذكي للمدارس</h1><p className="mt-2 text-sm leading-7 text-slate-300">التفعيل هنا هو مصدر صلاحية الخادم؛ عضوية المدرسة وحدها لا تفتح Smart Classroom.</p></header>{error?<div role="alert" className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{notice?<div className="rounded-xl bg-emerald-50 p-3 font-bold text-emerald-700">{notice}</div>:null}<section className="grid gap-4 md:grid-cols-[300px_1fr]"><div className="rounded-3xl border bg-white p-4 shadow-sm"><h2 className="flex items-center gap-2 font-black"><Building2 size={18}/>المدرسة</h2><div className="mt-3 space-y-2">{schools.map(s=><button key={s.id} type="button" onClick={()=>setSelected(s.id)} className={`w-full rounded-2xl border p-3 text-right font-black ${selected===s.id?'border-indigo-500 bg-indigo-50':'bg-white'}`}>{s.name}<div className="mt-1 text-[11px] text-gray-400">{s.code}</div></button>)}</div></div><div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">وحدة SMART_CLASSROOM</h2><label className="mt-5 flex cursor-pointer items-center justify-between rounded-2xl border bg-slate-50 p-4"><div><div className="font-black">الفصل الذكي مباشر</div><p className="mt-1 text-xs font-bold text-gray-500">يطبق على إنشاء الحصة، الانضمام، التحكم، التحليلات والاتصال اللحظي.</p></div><input aria-label="تفعيل الفصل الذكي" type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)} className="h-5 w-5"/></label><div className="mt-4 rounded-2xl bg-gray-50 p-4 text-xs font-bold leading-6 text-gray-600">الحالة الحالية: {contract?contract.status:'لا يوجد عقد بعد'} · revision {contract?.revision||0}</div><button type="button" onClick={()=>void save()} disabled={saving||!selected} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-black text-white disabled:opacity-40">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}حفظ العقد</button></div></section></main>;
}
