import {CheckCircle2,ChevronLeft,ChevronRight,ClipboardList,Plus,RefreshCcw,Search} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {useAuth} from '../../auth/state/AuthProvider';
import {contentClient} from '../../content/api/content-client';
import type {TaxonomyCore} from '../../content/api/content-types';
import {assessmentClient} from '../api/assessment-client';
import type {AssessmentSummary,AssessmentWorkflowStatus} from '../api/assessment-types';
import {AssessmentEditorPanel} from '../components/AssessmentEditorPanel';
const labels:Record<AssessmentWorkflowStatus,string>={draft:'مسودة',pending_review:'بانتظار المراجعة',approved:'معتمد',rejected:'مرفوض',archived:'مؤرشف'};
export function AssessmentAdminPage(){const {user,loading:authLoading,getCsrfToken}=useAuth();const admin=user?.roles.includes('admin')??false;const teacher=user?.roles.includes('teacher')??false;const [taxonomy,setTaxonomy]=useState<TaxonomyCore>({paths:[],subjects:[]});const[pathId,setPathId]=useState('');const[subjectId,setSubjectId]=useState('');const[status,setStatus]=useState<AssessmentWorkflowStatus|''>('');const[search,setSearch]=useState('');const[debounced,setDebounced]=useState('');const[page,setPage]=useState(1);const[rows,setRows]=useState<AssessmentSummary[]>([]);const[hasMore,setHasMore]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[editing,setEditing]=useState<string|null>(null);const[reload,setReload]=useState(0);
useEffect(()=>{const c=new AbortController();contentClient.taxonomyCore(c.signal).then(setTaxonomy).catch(()=>{});return()=>c.abort()},[]);
useEffect(()=>{const t=window.setTimeout(()=>{setDebounced(search.trim());setPage(1)},280);return()=>window.clearTimeout(t)},[search]);
const subjects=useMemo(()=>taxonomy.subjects.filter(s=>!pathId||s.pathId===pathId),[taxonomy,pathId]);useEffect(()=>{if(subjectId&&!subjects.some(s=>s.id===subjectId))setSubjectId('')},[subjects,subjectId]);
const waiting=teacher&&!admin&&(!pathId||!subjectId);
useEffect(()=>{if(authLoading||!user||(!admin&&!teacher)||waiting){setRows([]);return}const c=new AbortController();setBusy(true);setError('');assessmentClient.list({page,limit:50,pathId,subjectId,workflowStatus:status,search:debounced},c.signal).then(r=>{setRows(r.items);setHasMore(r.hasMore)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل الاختبارات')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[admin,authLoading,debounced,page,pathId,reload,status,subjectId,teacher,user,waiting]);
if(authLoading)return <main className="p-10 text-center font-black">جاري التحقق من الجلسة...</main>;if(!user||(!admin&&!teacher))return <main className="p-10 text-center font-black text-rose-700">هذه الشاشة متاحة للإدارة والمعلمين المخولين فقط.</main>;
if(editing!==null)return <AssessmentEditorPanel assessmentId={editing||undefined} taxonomy={taxonomy} initialPathId={pathId} initialSubjectId={subjectId} isAdmin={admin} lockScope={teacher&&!admin} getCsrfToken={getCsrfToken} onCancel={()=>setEditing(null)} onSaved={()=>{setEditing(null);setReload(x=>x+1)}}/>;
return <main dir="rtl" className="mx-auto max-w-7xl space-y-4"><section className="rounded-3xl bg-slate-950 p-5 text-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black text-amber-400">ASSESSMENT CENTER</p><h1 className="mt-1 text-2xl font-black">مركز الاختبارات</h1><p className="mt-1 text-sm text-slate-300">إنشاء الاختبارات وإدارتها ومراجعتها دون تحميل بنك الأسئلة كاملًا.</p></div><button onClick={()=>setEditing('')} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 font-black text-slate-950"><Plus size={18}/>اختبار جديد</button></div></section>
<section className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><select aria-label="المسار" value={pathId} onChange={e=>{setPathId(e.target.value);setPage(1)}} className="rounded-xl border p-2"><option value="">كل المسارات</option>{taxonomy.paths.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="المادة" value={subjectId} onChange={e=>{setSubjectId(e.target.value);setPage(1)}} className="rounded-xl border p-2"><option value="">كل المواد</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="الحالة" value={status} onChange={e=>{setStatus(e.target.value as AssessmentWorkflowStatus|'');setPage(1)}} className="rounded-xl border p-2"><option value="">كل الحالات</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><label className="relative lg:col-span-2"><Search className="absolute right-3 top-2.5" size={18}/><input aria-label="بحث الاختبارات" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالعنوان أو الكود" className="w-full rounded-xl border py-2 pr-10 pl-3"/></label></section>
{waiting?<div className="rounded-2xl bg-amber-50 p-5 font-bold text-amber-800">اختر المسار ثم المادة لعرض اختبارات نطاقك فقط.</div>:null}{error?<div className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}
<section className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div className="flex items-center gap-2 font-black"><ClipboardList size={20}/>الاختبارات المعروضة <span className="rounded-full bg-gray-100 px-2 py-1 text-xs">{rows.length}</span></div><button onClick={()=>setReload(x=>x+1)} aria-label="تحديث" className="rounded-lg p-2"><RefreshCcw size={17}/></button></div>{busy?<div className="p-8 text-center font-bold text-gray-500">جاري التحميل...</div>:rows.length===0&&!waiting?<div className="p-8 text-center text-gray-500">لا توجد اختبارات مطابقة.</div>:<div className="divide-y">{rows.map(x=><article key={x.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-black text-gray-900">{x.title}</h2><span className="rounded-full bg-gray-100 px-2 py-1 text-xs font-bold">{labels[x.workflowStatus]}</span>{x.isPublished?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700"><CheckCircle2 size={13}/>منشور</span>:null}</div><p className="mt-1 text-xs text-gray-400">{x.code} · الإصدار {x.currentVersion}</p></div><button onClick={()=>setEditing(x.id)} className="rounded-xl border px-4 py-2 text-sm font-black">فتح / تعديل</button></article>)}</div>}</section>
<div className="flex justify-between"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 disabled:opacity-40"><ChevronRight size={17}/>السابق</button><span className="py-2 text-sm font-bold">صفحة {page}</span><button disabled={!hasMore} onClick={()=>setPage(p=>p+1)} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 disabled:opacity-40">التالي<ChevronLeft size={17}/></button></div></main>}
