import{ClipboardList,Loader2,Play}from'lucide-react';
import{useEffect,useState}from'react';
import{useNavigate}from'react-router-dom';
import{useAuth}from'../../auth/state/AuthProvider';
import{assessmentAssignmentClient,type LearnerAssessmentAssignment}from'../api/assessment-assignment-client';
const key=(id:string)=>{const k=`assessment-assignment-start:${id}`;let v=sessionStorage.getItem(k);if(!v){v=crypto.randomUUID();sessionStorage.setItem(k,v)}return v};
export function AssessmentAssignmentsPage(){const{user,loading:authLoading,getCsrfToken}=useAuth();const nav=useNavigate();const[rows,setRows]=useState<LearnerAssessmentAssignment[]>([]);const[busy,setBusy]=useState(true);const[starting,setStarting]=useState('');const[error,setError]=useState('');
useEffect(()=>{if(authLoading)return;if(!user?.roles.includes('student')){setBusy(false);return}const c=new AbortController();setBusy(true);assessmentAssignmentClient.mine(1,30,c.signal).then(x=>setRows(x.items)).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل التكليفات')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[authLoading,user]);
async function start(row:LearnerAssessmentAssignment){setStarting(row.assignmentId);setError('');try{const csrf=await getCsrfToken();const x=await assessmentAssignmentClient.start(row.assignmentId,key(row.assignmentId),csrf);nav(`/assessment-attempts/${x.attempt.id}`)}catch(e){setError(e instanceof Error?e.message:'تعذر بدء التكليف')}finally{setStarting('')}}
if(authLoading||busy)return <main className="p-10 text-center font-black">جاري تحميل التكليفات...</main>;if(!user?.roles.includes('student'))return <main className="p-10 text-center font-black text-rose-700">هذه الشاشة مخصصة للطالب.</main>;
return <main dir="rtl" className="min-h-[calc(100vh-5rem)] bg-gray-50 px-3 py-6 sm:px-6"><div className="mx-auto max-w-4xl space-y-4"><header className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-amber-400"><ClipboardList size={20}/><span className="text-xs font-black">DIRECTED ASSESSMENTS</span></div><h1 className="mt-2 text-2xl font-black">الاختبارات الموجهة إليك</h1><p className="mt-1 text-sm text-slate-300">تظهر فقط التكليفات التي يثبت الخادم أنها موجهة لك أو لفصلك وفي نافذة زمنية فعالة.</p></header>{error?<div className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{rows.length===0?<section className="rounded-2xl border border-dashed bg-white p-10 text-center font-bold text-gray-500">لا توجد تكليفات اختبار فعالة الآن.</section>:<section className="grid gap-3 sm:grid-cols-2">{rows.map(row=><article key={row.assignmentId} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-gray-900">{row.title}</h2><p className="mt-1 text-xs font-bold text-gray-500">المحاولات {row.attemptCount} من {row.maxAttempts}</p></div><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-black text-indigo-700">v{row.assessmentVersion}</span></div>{row.supervisorMessage?<p className="mt-3 rounded-xl bg-gray-50 p-3 text-sm font-bold leading-6 text-gray-600">{row.supervisorMessage}</p>:null}<button disabled={!row.canStart||starting===row.assignmentId} onClick={()=>void start(row)} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-black text-white disabled:opacity-40">{starting===row.assignmentId?<Loader2 size={18} className="animate-spin"/>:<Play size={18}/>} {row.canStart?'ابدأ التكليف':'استُنفدت المحاولات'}</button></article>)}</section>}</div></main>}
