import {Loader2,RadioTower} from 'lucide-react';
import {useEffect,useState} from 'react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from '../../auth/state/AuthProvider';
import {assessmentSessionClient} from '../api/assessment-session-client';
import type {LiveJoin} from '../api/assessment-session-client';
const startKey=(id:string)=>{const k='assessment-live-start:'+id;let v=sessionStorage.getItem(k);if(!v){v=crypto.randomUUID();sessionStorage.setItem(k,v)}return v};
export function LiveAssessmentJoinPage(){const{user,loading,getCsrfToken}=useAuth();const navigate=useNavigate();const[params,setParams]=useSearchParams();const[code,setCode]=useState(params.get('code')||'');const[session,setSession]=useState<LiveJoin|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
useEffect(()=>{const q=params.get('code')||'';if(loading||!user||!q)return;const c=new AbortController();setBusy(true);setError('');assessmentSessionClient.live(q,c.signal).then(x=>setSession(x.session)).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'الجلسة غير متاحة')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[loading,params,user]);
async function start(){if(!session)return;setBusy(true);try{const csrf=await getCsrfToken();const out=await assessmentSessionClient.startLive(session.sessionId,startKey(session.sessionId),csrf);navigate('/assessment-attempts/'+out.attempt.id)}catch(e){setError(e instanceof Error?e.message:'تعذر بدء الجلسة')}finally{setBusy(false)}}
if(loading)return <main className="p-10 text-center font-black">جاري التحقق من الجلسة...</main>;if(!user||!user.roles.includes('student'))return <main className="p-10 text-center font-black text-rose-700">سجّل الدخول بحساب طالب للانضمام للجلسة المباشرة.</main>;
return <main dir="rtl" className="mx-auto max-w-xl p-5"><section className="rounded-3xl border bg-white p-6 shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-cyan-50 text-cyan-700"><RadioTower size={28}/></div><h1 className="mt-4 text-center text-2xl font-black">الانضمام لاختبار مباشر</h1><div className="mt-5 flex gap-2"><input aria-label="رمز الجلسة المباشرة" value={code} onChange={e=>setCode(e.target.value)} className="min-w-0 flex-1 rounded-xl border p-3 text-center font-mono font-black tracking-widest"/><button onClick={()=>setParams({code:code.trim()})} className="rounded-xl bg-slate-950 px-4 font-black text-white">تحقق</button></div>{busy?<div className="mt-5 flex justify-center"><Loader2 className="animate-spin"/></div>:null}{error?<div className="mt-4 rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{session?<div className="mt-5 rounded-2xl bg-gray-50 p-4"><h2 className="font-black">{session.title}</h2><p className="mt-1 text-sm font-bold text-gray-500">المحاولات {session.attemptCount} من {session.maxAttempts}</p><button disabled={!session.canStart||busy} onClick={()=>void start()} className="mt-4 w-full rounded-xl bg-cyan-600 p-3 font-black text-white disabled:opacity-40">{session.canStart?'ابدأ الاختبار':'استُنفدت المحاولات'}</button></div>:null}</section></main>}
