import {BadgeCheck,ChevronRight,Loader2,Percent,ReceiptText,ShieldCheck} from 'lucide-react';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useAuth} from '../../auth/state/AuthProvider';
import {commerceClient} from '../api/commerce-client';
import type {CommerceCheckoutQuote,CommercePaymentMethod,CommercePaymentRequest} from '../api/commerce-types';

const money=(minor:number,currency:string)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency}).format(minor/100);

export function CheckoutPage(){
 const{productId=''}=useParams();const{user,loading:getAuthLoading,getCsrfToken}=useAuth();
 const[quote,setQuote]=useState<CommerceCheckoutQuote|null>(null);const[request,setRequest]=useState<CommercePaymentRequest|null>(null);
 const[discount,setDiscount]=useState('');const[method,setMethod]=useState<CommercePaymentMethod>('transfer');const[country,setCountry]=useState('SA');
 const[transferReference,setTransferReference]=useState('');const[walletNumber,setWalletNumber]=useState('');const[notes,setNotes]=useState('');
 const[busy,setBusy]=useState(false);const[error,setError]=useState('');const idempotency=useRef('');
 if(!idempotency.current)idempotency.current=crypto.randomUUID();

 useEffect(()=>{if(getAuthLoading||!user||!productId)return;const c=new AbortController();setBusy(true);setError('');
  commerceClient.quote(productId,'',c.signal).then(x=>setQuote(x.quote)).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تجهيز طلب الشراء')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});
  return()=>c.abort()
 },[getAuthLoading,productId,user]);

 const evidenceReady=useMemo(()=>{
  if(method==='transfer')return transferReference.trim().length>0||notes.trim().length>=4;
  if(method==='wallet')return walletNumber.trim().length>0||notes.trim().length>=4;
  return true;
 },[method,notes,transferReference,walletNumber]);

 async function applyDiscount(){if(!productId)return;setBusy(true);setError('');try{const out=await commerceClient.quote(productId,discount.trim());setQuote(out.quote)}catch(e){setError(e instanceof Error?e.message:'كود الخصم غير صالح')}finally{setBusy(false)}}
 async function submit(){if(!quote||!evidenceReady)return;setBusy(true);setError('');try{const csrf=await getCsrfToken();const out=await commerceClient.createPaymentRequest({productId:quote.productId,discountCode:quote.discountCode,paymentMethod:method,paymentCountry:country,transferReference:method==='transfer'?transferReference.trim():'',walletNumber:method==='wallet'?walletNumber.trim():'',notes:notes.trim(),idempotencyKey:idempotency.current},csrf);setRequest(out.request)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء طلب الدفع')}finally{setBusy(false)}}

 if(getAuthLoading)return <main className="p-10 text-center font-black">جاري التحقق...</main>;
 if(!user)return <main dir="rtl" className="mx-auto max-w-lg p-6"><div className="rounded-2xl border bg-white p-6 text-center"><h1 className="text-xl font-black">سجل الدخول لإكمال الشراء</h1><Link to="/login" className="mt-4 inline-flex rounded-xl bg-slate-950 px-4 py-2.5 font-black text-white">تسجيل الدخول</Link></div></main>;
 if(request)return <main dir="rtl" className="mx-auto max-w-xl p-5"><section className="rounded-3xl border bg-white p-7 text-center shadow-sm"><BadgeCheck className="mx-auto text-emerald-600" size={46}/><h1 className="mt-3 text-2xl font-black">تم إنشاء طلب الدفع</h1><p className="mt-3 text-sm font-bold text-gray-500">{request.gatewayMode==='webhook'?'سيتم فتح الوصول فقط بعد تأكيد مزود الدفع الموقّع.':'سيُراجع الطلب قبل فتح الوصول.'}</p><div className="mt-5 rounded-2xl bg-gray-50 p-4"><div className="text-sm font-black">{request.productName}</div><div className="mt-1 text-2xl font-black">{money(request.finalAmountMinor,request.currency)}</div><div className="mt-1 text-xs font-bold text-gray-500">{request.status}</div></div><Link to="/" className="mt-5 inline-flex items-center gap-1 font-black text-indigo-700">العودة للمنصة <ChevronRight size={16}/></Link></section></main>;

 return <main dir="rtl" className="min-h-[calc(100vh-5rem)] bg-gray-50 px-3 py-6 sm:px-6"><div className="mx-auto max-w-2xl space-y-4"><header className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-amber-400"><ReceiptText size={20}/><span className="text-xs font-black">SERVER-OWNED CHECKOUT</span></div><h1 className="mt-2 text-2xl font-black">إتمام طلب الشراء</h1><p className="mt-2 text-sm leading-7 text-slate-300">السعر والخصم والعملة يعاد حلها من الخادم؛ الواجهة لا ترسل مبلغًا قابلًا للتلاعب.</p></header>{error?<div role="alert" className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{busy&&!quote?<div className="rounded-2xl bg-white p-8 text-center font-black">جاري تجهيز السعر...</div>:quote?<><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-black text-indigo-600">{quote.productType}</div><h2 className="mt-1 text-xl font-black">{quote.productName}</h2></div><div className="text-left"><div className="text-xs font-bold text-gray-400">السعر النهائي</div><div className="text-2xl font-black">{money(quote.finalAmountMinor,quote.currency)}</div></div></div>{quote.discountAmountMinor>0?<div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-gray-50 p-3"><div className="text-xs font-bold text-gray-500">قبل الخصم</div><div className="font-black">{money(quote.originalAmountMinor,quote.currency)}</div></div><div className="rounded-xl bg-emerald-50 p-3 text-emerald-800"><div className="text-xs font-bold">الخصم {quote.discountCode}</div><div className="font-black">- {money(quote.discountAmountMinor,quote.currency)}</div></div></div>:null}</section>
 <section className="space-y-3 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2 font-black"><Percent size={18}/>كود الخصم</div><div className="flex gap-2"><input aria-label="كود الخصم" value={discount} onChange={e=>setDiscount(e.target.value.toUpperCase())} className="min-w-0 flex-1 rounded-xl border p-2.5" placeholder="SAVE10"/><button type="button" disabled={busy||!discount.trim()} onClick={()=>void applyDiscount()} className="rounded-xl border px-4 py-2 font-black disabled:opacity-40">تطبيق</button></div></section>
 <section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">وسيلة الدفع</h2><div className="grid grid-cols-3 gap-2">{(['card','transfer','wallet'] as CommercePaymentMethod[]).map(v=><button type="button" key={v} onClick={()=>setMethod(v)} className={`rounded-xl border px-3 py-2.5 text-sm font-black ${method===v?'border-indigo-400 bg-indigo-50 text-indigo-800':''}`}>{v==='card'?'بطاقة':v==='transfer'?'تحويل':'محفظة'}</button>)}</div><select aria-label="دولة الدفع" value={country} onChange={e=>setCountry(e.target.value)} className="w-full rounded-xl border p-2.5"><option value="SA">السعودية</option><option value="EG">مصر</option></select>{method==='transfer'?<input aria-label="مرجع التحويل" value={transferReference} onChange={e=>setTransferReference(e.target.value)} placeholder="رقم مرجع التحويل" className="w-full rounded-xl border p-2.5"/>:null}{method==='wallet'?<input aria-label="رقم المحفظة" value={walletNumber} onChange={e=>setWalletNumber(e.target.value)} placeholder="رقم المحفظة / الجوال" className="w-full rounded-xl border p-2.5"/>:null}<textarea aria-label="ملاحظات الدفع" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="ملاحظات أو دليل إضافي" className="w-full rounded-xl border p-2.5"/><div className="rounded-xl bg-blue-50 p-3 text-xs font-bold leading-6 text-blue-900"><ShieldCheck size={16} className="mb-1"/>فتح الوصول لا يحدث من المتصفح. الاعتماد اليدوي أو حدث مزود موثوق فقط يمكنه إنشاء Entitlement.</div><button type="button" disabled={busy||!evidenceReady} onClick={()=>void submit()} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 p-3 font-black text-white disabled:opacity-40">{busy?<Loader2 size={18} className="animate-spin"/>:<ReceiptText size={18}/>}إنشاء طلب الدفع</button></section></>:null}</div></main>;
}
