import {BadgeDollarSign,CheckCircle2,KeyRound,Loader2,PackagePlus,Percent,ReceiptText,RefreshCcw,Save,ShieldCheck,XCircle} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {useAuth} from '../../auth/state/AuthProvider';
import {commerceClient} from '../api/commerce-client';
import type {CommerceAccessCode,CommerceContentType,CommerceDiscount,CommerceDiscountWrite,CommerceEntitlement,CommercePaymentRequest,CommerceProduct,CommerceProductWrite,CommerceSchoolSeat} from '../api/commerce-types';

const money=(minor:number,currency:string)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency}).format(minor/100);
const productWrite=(p:CommerceProduct,priceMinor:number,accessMode:'free'|'paid'):CommerceProductWrite=>({
 code:p.code,productType:p.productType,name:p.name,description:p.description,status:p.status,accessMode,
 priceMinor:accessMode==='free'?0:Math.max(1,Math.trunc(priceMinor)),currency:p.currency,courseId:p.courseId,isVisible:p.isVisible,
 package:p.package?{packageKind:p.package.packageKind,seatCapacity:p.package.seatCapacity,validityDays:p.package.validityDays,items:p.package.items||[]}:undefined,
});

export function CommerceAdminPage(){
 const{user,loading:authLoading,getCsrfToken}=useAuth();
 const[products,setProducts]=useState<CommerceProduct[]>([]);const[entitlements,setEntitlements]=useState<CommerceEntitlement[]>([]);
 const[discounts,setDiscounts]=useState<CommerceDiscount[]>([]);const[accessCodes,setAccessCodes]=useState<CommerceAccessCode[]>([]);const[seats,setSeats]=useState<CommerceSchoolSeat[]>([]);const[paymentRequests,setPaymentRequests]=useState<CommercePaymentRequest[]>([]);
 const[busy,setBusy]=useState(true);const[saving,setSaving]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
 const[prices,setPrices]=useState<Record<string,number>>({});
 const[pkgName,setPkgName]=useState('');const[pkgCode,setPkgCode]=useState('');const[pkgPrice,setPkgPrice]=useState(0);const[pkgContent,setPkgContent]=useState<CommerceContentType>('all');
 const[subjectType,setSubjectType]=useState<'user'|'school'>('user');const[subjectId,setSubjectId]=useState('');const[grantProduct,setGrantProduct]=useState('');
 const[activationCode,setActivationCode]=useState('');const[activationProduct,setActivationProduct]=useState('');const[activationUses,setActivationUses]=useState(1);const[activationExpires,setActivationExpires]=useState('');\n const[seatSchoolEntitlement,setSeatSchoolEntitlement]=useState('');const[seatUser,setSeatUser]=useState('');\n const[discountCode,setDiscountCode]=useState('');const[discountPercent,setDiscountPercent]=useState(10);const[discountScope,setDiscountScope]=useState<'all'|'product'>('all');const[discountProduct,setDiscountProduct]=useState('');
 const[reload,setReload]=useState(0);

 useEffect(()=>{if(authLoading||!user||!user.roles.includes('admin'))return;const c=new AbortController();setBusy(true);setError('');
  Promise.all([commerceClient.products(1,100,'','',c.signal),commerceClient.entitlements(1,50,c.signal),commerceClient.discounts(1,50,'','',c.signal),commerceClient.paymentRequests(1,50,'pending',c.signal),commerceClient.accessCodes(1,50,c.signal)]).then(([p,e,d,r,a])=>{setProducts(p.items);setEntitlements(e.items);setDiscounts(d.items);setPaymentRequests(r.items);setAccessCodes(a.items);setPrices(Object.fromEntries(p.items.map(x=>[x.id,x.priceMinor])))}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل Commerce')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()
 },[authLoading,reload,user]);

 useEffect(()=>{if(!seatSchoolEntitlement){setSeats([]);return}const c=new AbortController();commerceClient.schoolSeats(seatSchoolEntitlement,1,50,c.signal).then(r=>setSeats(r.items)).catch(()=>setSeats([]));return()=>c.abort()},[reload,seatSchoolEntitlement]);
 const activeProducts=useMemo(()=>products.filter(x=>x.status==='active'),[products]);
 async function savePolicy(row:CommerceProduct,mode:'free'|'paid'){
  setSaving(row.id);setError('');setNotice('');try{const csrf=await getCsrfToken();await commerceClient.updateProduct(row,productWrite(row,prices[row.id]??row.priceMinor,mode),csrf);setNotice('تم حفظ سياسة الوصول من الخادم.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المنتج')}finally{setSaving('')}
 }
 async function createPackage(){
  const name=pkgName.trim(),code=pkgCode.trim().toUpperCase();if(!name||!code){setError('اكتب اسم الباقة وكودها.');return}
  setSaving('package');setError('');try{const csrf=await getCsrfToken();await commerceClient.createProduct({code,productType:'package',name,description:'',status:'active',accessMode:'paid',priceMinor:Math.max(1,Math.trunc(pkgPrice)),currency:'SAR',courseId:'',isVisible:true,package:{packageKind:'bundle',seatCapacity:null,validityDays:null,items:[{scopeType:pkgContent==='all'?'all':'content_type',courseId:'',pathId:'',subjectId:'',contentType:pkgContent==='all'?'':pkgContent}]}},csrf);setPkgName('');setPkgCode('');setPkgPrice(0);setNotice('تم إنشاء الباقة.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الباقة')}finally{setSaving('')}
 }
 async function grant(){
  if(!subjectId.trim()||!grantProduct){setError('حدد المستفيد والمنتج.');return}
  setSaving('grant');setError('');try{const csrf=await getCsrfToken();await commerceClient.grant({subjectType,userId:subjectType==='user'?subjectId.trim():'',schoolId:subjectType==='school'?subjectId.trim():'',productId:grantProduct,expiresAt:null,idempotencyKey:crypto.randomUUID()},csrf);setSubjectId('');setNotice('تم منح الوصول يدويًا مع سجل قابل للتدقيق.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر منح الوصول')}finally{setSaving('')}
 }
 async function revoke(row:CommerceEntitlement){
  setSaving(row.id);setError('');try{const csrf=await getCsrfToken();await commerceClient.revoke(row,'إلغاء يدوي من الإدارة',csrf);setNotice('تم إلغاء المنحة.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إلغاء المنحة')}finally{setSaving('')}
 }
 function discountWrite(row:CommerceDiscount,status=row.status):CommerceDiscountWrite{return {code:row.code,label:row.label,discountType:row.discountType,percentageBps:row.percentageBps,fixedMinor:row.fixedMinor,status,minAmountMinor:row.minAmountMinor,maxRedemptions:row.maxRedemptions,startsAt:row.startsAt,expiresAt:row.expiresAt,scopes:row.scopes}}
 async function createActivationCode(){
  const code=activationCode.trim().toUpperCase();if(!code||!activationProduct||!activationExpires){setError('حدد كود التفعيل والباقة وتاريخ الانتهاء.');return}
  setSaving('access-code');setError('');setNotice('');try{const csrf=await getCsrfToken();await commerceClient.createAccessCode({code,productId:activationProduct,schoolId:'',maxUses:Math.max(1,Math.trunc(activationUses)),expiresAt:new Date(activationExpires).toISOString()},csrf);setActivationCode('');setActivationProduct('');setActivationUses(1);setActivationExpires('');setNotice('تم إنشاء كود التفعيل.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء كود التفعيل')}finally{setSaving('')}
 }
 async function toggleActivationCode(row:CommerceAccessCode){setSaving(row.id);setError('');try{const csrf=await getCsrfToken();await commerceClient.setAccessCodeStatus(row,row.status==='active'?'paused':'active',csrf);setNotice('تم تحديث حالة كود التفعيل.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث كود التفعيل')}finally{setSaving('')}}
 async function assignSeat(){if(!seatSchoolEntitlement||!seatUser.trim()){setError('حدد منحة المدرسة والمستخدم.');return}setSaving('seat');setError('');try{const csrf=await getCsrfToken();await commerceClient.assignSchoolSeat(seatSchoolEntitlement,seatUser.trim(),csrf);setSeatUser('');setNotice('تم تخصيص المقعد وربط منحة مستخدم قابلة للتدقيق.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر تخصيص المقعد')}finally{setSaving('')}}
 async function revokeSeat(row:CommerceSchoolSeat){setSaving(row.id);setError('');try{const csrf=await getCsrfToken();await commerceClient.revokeSchoolSeat(row,'إلغاء مقعد من الإدارة',csrf);setNotice('تم إلغاء المقعد والمنحة المرتبطة.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إلغاء المقعد')}finally{setSaving('')}}
 async function createDiscount(){
  const code=discountCode.trim().toUpperCase(),percent=Math.max(1,Math.min(100,discountPercent));if(!code||(discountScope==='product'&&!discountProduct)){setError('اكتب كود الخصم وحدد المنتج عند استخدام نطاق منتج.');return}
  setSaving('discount');setError('');setNotice('');try{const csrf=await getCsrfToken();await commerceClient.createDiscount({code,label:'',discountType:'percentage',percentageBps:Math.round(percent*100),fixedMinor:null,status:'active',minAmountMinor:0,maxRedemptions:0,startsAt:null,expiresAt:null,scopes:[discountScope==='all'?{scopeType:'all',productId:'',productType:''}:{scopeType:'product',productId:discountProduct,productType:''}]},csrf);setDiscountCode('');setDiscountProduct('');setNotice('تم إنشاء كود الخصم من Commerce.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء كود الخصم')}finally{setSaving('')}
 }
 async function toggleDiscount(row:CommerceDiscount){setSaving(row.id);setError('');try{const csrf=await getCsrfToken();await commerceClient.updateDiscount(row,discountWrite(row,row.status==='active'?'paused':'active'),csrf);setNotice('تم تحديث حالة كود الخصم.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث كود الخصم')}finally{setSaving('')}}
 async function reviewPayment(row:CommercePaymentRequest,status:'paid'|'rejected'){
  const evidence=status==='paid'?(window.prompt('أدخل مرجع/دليل الاعتماد الإداري (6 أحرف على الأقل):','manual-review')||''):'';if(status==='paid'&&evidence.trim().length<6){setError('الاعتماد اليدوي يحتاج دليلًا واضحًا.');return}
  setSaving(row.id);setError('');setNotice('');try{const csrf=await getCsrfToken();await commerceClient.reviewPayment(row,status,status==='paid'?'اعتماد يدوي موثق':'رفض إداري',evidence.trim(),csrf);setNotice(status==='paid'?'تم اعتماد الطلب وإنشاء صلاحية الوصول من الخادم.':'تم رفض الطلب وإطلاق حجز الخصم.');setReload(x=>x+1)}catch(e){setError(e instanceof Error?e.message:'تعذر مراجعة طلب الدفع')}finally{setSaving('')}
 }

 if(authLoading)return <main className="p-10 text-center font-black">جاري التحقق...</main>;
 if(!user||!user.roles.includes('admin'))return <main className="p-10 text-center font-black text-rose-700">هذه الشاشة لمدير المنصة فقط.</main>;
 return <main dir="rtl" className="mx-auto max-w-6xl space-y-5">
  <header className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-amber-400"><BadgeDollarSign size={20}/><span className="text-xs font-black">COMMERCE CONTROL</span></div><h1 className="mt-2 text-2xl font-black">المنتجات والخصومات وطلبات الدفع</h1><p className="mt-2 text-sm leading-7 text-slate-300">السعر والخصم وقرار منح الوصول سلطة الخادم فقط. الاعتماد اليدوي يحتاج دليلًا، والـwebhook لا يُقبل إلا بتوقيع صحيح.</p></header>
  {error?<div role="alert" className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{notice?<div className="rounded-xl bg-emerald-50 p-3 font-bold text-emerald-700">{notice}</div>:null}
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h2 className="font-black">سياسة Course access</h2><button type="button" onClick={()=>setReload(x=>x+1)} className="inline-flex items-center gap-1 text-sm font-black text-indigo-700"><RefreshCcw size={15}/>تحديث</button></div>{busy?<div className="p-8 text-center font-bold text-gray-500">جاري التحميل...</div>:<div className="divide-y">{products.filter(x=>x.productType==='course').map(row=><article key={row.id} className="grid gap-3 p-4 md:grid-cols-[1fr_140px_150px_auto] md:items-center"><div><div className="font-black text-gray-900">{row.name}</div><div className="mt-1 text-xs font-bold text-gray-400">{row.code} · {row.accessMode==='free'?'مجاني':'مدفوع'}</div></div><input aria-label={`سعر ${row.name}`} type="number" min={0} value={prices[row.id]??0} onChange={e=>setPrices(v=>({...v,[row.id]:Number(e.target.value)||0}))} className="rounded-xl border p-2 text-sm"/><div className="text-sm font-black">{money(row.priceMinor,row.currency)}</div><div className="flex gap-2"><button type="button" disabled={saving===row.id} onClick={()=>void savePolicy(row,'free')} className="rounded-xl border px-3 py-2 text-xs font-black disabled:opacity-40">مجاني</button><button type="button" disabled={saving===row.id} onClick={()=>void savePolicy(row,'paid')} className="inline-flex items-center gap-1 rounded-xl bg-slate-950 px-3 py-2 text-xs font-black text-white disabled:opacity-40">{saving===row.id?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>}مدفوع</button></div></article>)}</div>}</section>

  <section className="grid gap-4 lg:grid-cols-2">
   <div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><Percent size={18}/>إنشاء كود خصم</div><input aria-label="كود الخصم الإداري" value={discountCode} onChange={e=>setDiscountCode(e.target.value.toUpperCase())} placeholder="SAVE10" className="w-full rounded-xl border p-2.5 font-mono"/><input aria-label="نسبة الخصم" type="number" min={1} max={100} value={discountPercent} onChange={e=>setDiscountPercent(Number(e.target.value)||1)} className="w-full rounded-xl border p-2.5"/><select aria-label="نطاق الخصم" value={discountScope} onChange={e=>setDiscountScope(e.target.value as 'all'|'product')} className="w-full rounded-xl border p-2.5"><option value="all">كل المنتجات</option><option value="product">منتج محدد</option></select>{discountScope==='product'?<select aria-label="منتج الخصم" value={discountProduct} onChange={e=>setDiscountProduct(e.target.value)} className="w-full rounded-xl border p-2.5"><option value="">اختر المنتج</option>{activeProducts.filter(x=>x.accessMode==='paid').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>:null}<button type="button" disabled={saving==='discount'} onClick={()=>void createDiscount()} className="inline-flex items-center gap-2 rounded-xl bg-fuchsia-600 px-4 py-2.5 font-black text-white disabled:opacity-40"><Percent size={17}/>إنشاء الخصم</button></div>
   <div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4 font-black">أكواد الخصم الحالية</div><div className="max-h-80 divide-y overflow-y-auto">{discounts.length===0?<div className="p-6 text-center text-sm font-bold text-gray-500">لا توجد أكواد خصم.</div>:discounts.map(row=><article key={row.id} className="flex items-center justify-between gap-3 p-3"><div><div className="font-black">{row.code}</div><div className="text-xs font-bold text-gray-400">{row.discountType==='percentage'?String((row.percentageBps||0)/100)+'%':String(row.fixedMinor||0)+' minor'} · محجوز {row.reservedCount} · مستخدم {row.redeemedCount}</div></div><button type="button" disabled={saving===row.id} onClick={()=>void toggleDiscount(row)} className="rounded-xl border px-3 py-2 text-xs font-black disabled:opacity-40">{row.status==='active'?'إيقاف':'تفعيل'}</button></article>)}</div></div>
  </section>

  <section className="grid gap-4 lg:grid-cols-2">
   <div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><KeyRound size={18}/>أكواد التفعيل</div><input aria-label="كود التفعيل الإداري" value={activationCode} onChange={e=>setActivationCode(e.target.value.toUpperCase())} placeholder="SCHOOL-2026" className="w-full rounded-xl border p-2.5 font-mono"/><select aria-label="باقة كود التفعيل" value={activationProduct} onChange={e=>setActivationProduct(e.target.value)} className="w-full rounded-xl border p-2.5"><option value="">اختر باقة</option>{activeProducts.filter(x=>x.accessMode==='paid'&&Boolean(x.package)).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input aria-label="عدد استخدامات كود التفعيل" type="number" min={1} value={activationUses} onChange={e=>setActivationUses(Number(e.target.value)||1)} className="w-full rounded-xl border p-2.5"/><input aria-label="انتهاء كود التفعيل" type="datetime-local" value={activationExpires} onChange={e=>setActivationExpires(e.target.value)} className="w-full rounded-xl border p-2.5"/><button type="button" disabled={saving==='access-code'} onClick={()=>void createActivationCode()} className="rounded-xl bg-amber-500 px-4 py-2.5 font-black text-white disabled:opacity-40">إنشاء كود تفعيل</button><div className="max-h-56 divide-y overflow-y-auto">{accessCodes.map(row=><div key={row.id} className="flex items-center justify-between py-2 text-sm"><div><strong>{row.code}</strong><div className="text-xs text-gray-500">{row.currentUses}/{row.maxUses} · {row.status}</div></div><button type="button" onClick={()=>void toggleActivationCode(row)} className="rounded-lg border px-2 py-1 text-xs font-black">{row.status==='active'?'إيقاف':'تفعيل'}</button></div>)}</div></div>
   <div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><ShieldCheck size={18}/>مقاعد المدارس المحدودة</div><select aria-label="منحة المدرسة للمقاعد" value={seatSchoolEntitlement} onChange={e=>setSeatSchoolEntitlement(e.target.value)} className="w-full rounded-xl border p-2.5"><option value="">اختر منحة مدرسة</option>{entitlements.filter(x=>x.subjectType==='school'&&x.status==='active').map(x=><option key={x.id} value={x.id}>{x.schoolId} · {x.productId}</option>)}</select><input aria-label="مستخدم المقعد" value={seatUser} onChange={e=>setSeatUser(e.target.value)} placeholder="User UUID" className="w-full rounded-xl border p-2.5"/><button type="button" disabled={saving==='seat'} onClick={()=>void assignSeat()} className="rounded-xl bg-emerald-600 px-4 py-2.5 font-black text-white disabled:opacity-40">تخصيص مقعد</button><div className="max-h-56 divide-y overflow-y-auto">{seats.map(row=><div key={row.id} className="flex items-center justify-between py-2 text-sm"><div><strong>{row.userId}</strong><div className="text-xs text-gray-500">{row.status}</div></div>{row.status==='active'?<button type="button" disabled={saving===row.id} onClick={()=>void revokeSeat(row)} className="rounded-lg border border-rose-200 px-2 py-1 text-xs font-black text-rose-700">إلغاء</button>:null}</div>)}</div></div>
  </section>

  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center gap-2 border-b p-4 font-black"><ReceiptText size={18}/>طلبات الدفع المعلقة</div><div className="divide-y">{paymentRequests.length===0?<div className="p-6 text-center text-sm font-bold text-gray-500">لا توجد طلبات معلقة.</div>:paymentRequests.map(row=><article key={row.id} className="grid gap-3 p-4 md:grid-cols-[1fr_auto] md:items-center"><div><div className="font-black">{row.productName}</div><div className="mt-1 text-xs font-bold text-gray-400">{row.userId} · {money(row.finalAmountMinor,row.currency)} · {row.paymentMethod} · {row.providerCode}</div>{row.discountCode?<div className="mt-1 text-xs font-black text-fuchsia-700">خصم {row.discountCode}: {money(row.discountAmountMinor,row.currency)}</div>:null}</div><div className="flex gap-2"><button type="button" disabled={saving===row.id} onClick={()=>void reviewPayment(row,'paid')} className="inline-flex items-center gap-1 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white disabled:opacity-40"><CheckCircle2 size={15}/>اعتماد</button><button type="button" disabled={saving===row.id} onClick={()=>void reviewPayment(row,'rejected')} className="inline-flex items-center gap-1 rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-700 disabled:opacity-40"><XCircle size={15}/>رفض</button></div></article>)}</div></section>

  <section className="grid gap-4 lg:grid-cols-2">
   <div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><PackagePlus size={18}/>إنشاء باقة</div><input aria-label="كود الباقة" value={pkgCode} onChange={e=>setPkgCode(e.target.value)} placeholder="QUDRAT-ALL" className="w-full rounded-xl border p-2.5"/><input aria-label="اسم الباقة" value={pkgName} onChange={e=>setPkgName(e.target.value)} placeholder="باقة القدرات" className="w-full rounded-xl border p-2.5"/><input aria-label="سعر الباقة بالهللة" type="number" min={1} value={pkgPrice} onChange={e=>setPkgPrice(Number(e.target.value)||0)} className="w-full rounded-xl border p-2.5"/><select aria-label="نطاق محتوى الباقة" value={pkgContent} onChange={e=>setPkgContent(e.target.value as CommerceContentType)} className="w-full rounded-xl border p-2.5"><option value="all">كل المنصة</option><option value="courses">الدورات</option><option value="foundation">التأسيس</option><option value="tests">الاختبارات</option><option value="mock_exams">المحاكيات</option><option value="library">المكتبة</option><option value="banks">بنوك الأسئلة</option></select><button type="button" disabled={saving==='package'} onClick={()=>void createPackage()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-black text-white disabled:opacity-40"><PackagePlus size={17}/>إنشاء</button></div>
   <div className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex items-center gap-2 font-black"><KeyRound size={18}/>منحة وصول يدوية</div><select aria-label="نوع المستفيد" value={subjectType} onChange={e=>setSubjectType(e.target.value as 'user'|'school')} className="w-full rounded-xl border p-2.5"><option value="user">مستخدم</option><option value="school">مدرسة</option></select><input aria-label="معرف المستفيد" value={subjectId} onChange={e=>setSubjectId(e.target.value)} placeholder="UUID" className="w-full rounded-xl border p-2.5"/><select aria-label="المنتج الممنوح" value={grantProduct} onChange={e=>setGrantProduct(e.target.value)} className="w-full rounded-xl border p-2.5"><option value="">اختر المنتج</option>{activeProducts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button type="button" disabled={saving==='grant'} onClick={()=>void grant()} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 font-black text-white disabled:opacity-40"><ShieldCheck size={17}/>منح الوصول</button></div>
  </section>

  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-4 font-black">آخر المنح</div><div className="divide-y">{entitlements.length===0?<div className="p-6 text-center text-sm font-bold text-gray-500">لا توجد منح.</div>:entitlements.map(row=><article key={row.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-black">{row.subjectType==='user'?row.userId:row.schoolId}</div><div className="text-xs font-bold text-gray-400">{row.productId} · {row.status}</div></div>{row.status==='active'?<button type="button" disabled={saving===row.id} onClick={()=>void revoke(row)} className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-black text-rose-700 disabled:opacity-40">إلغاء المنحة</button>:null}</article>)}</div></section>
 </main>;
}
