import {expect,test,type Page,type Route} from '@playwright/test';
const admin={id:'admin-1',email:'admin@example.com',name:'مدير المنصة',status:'active',avatarUrl:'',emailVerified:true,role:'admin',roles:['admin']};
const teacher={...admin,id:'teacher-1',role:'teacher',roles:['teacher'],name:'معلم'};
const taxonomy={paths:[{id:'path-1',code:'QDR',name:'القدرات',description:'',sortOrder:1}],subjects:[{id:'subject-1',pathId:'path-1',code:'QNT',name:'الكمي',sortOrder:1}]};
const summary={id:'assessment-1',code:'QNT-MOCK-1',title:'محاكي القدرات الكمي',pathId:'path-1',subjectId:'subject-1',kind:'normal',workflowStatus:'draft',ownerType:'platform',revision:2,currentVersion:1,isPublished:false,updatedAt:'2026-09-26T10:00:00Z'};
const detail={...summary,ownerUserId:'',ownerSchoolId:'',assignedTeacherId:'',reviewerNotes:'',isVisible:true,version:{version:1,title:summary.title,description:'اختبار تجريبي',pathId:'path-1',subjectId:'subject-1',kind:'normal',normalMode:'practice',showExplanations:true,showAnswers:true,showResultsReport:true,returnToSourceOnFinish:false,maxAttempts:2,passingScore:60,timeLimitSeconds:null,randomizeQuestions:false,randomizeOptions:false,showProgressBar:true,requireAnswerBeforeNext:false,allowQuestionReview:true,optionLayout:'vertical',mockCategory:'',mockTargetScore:null,mockStrictSectionLock:null,mockPresentationMode:'',presentation:{},revisionNote:''},sections:[],questions:[{questionId:'q-1',questionVersion:3,sectionId:'',sortOrder:1,points:1}]};
function json(r:Route,b:unknown,s=200){return r.fulfill({status:s,contentType:'application/json',body:JSON.stringify(b)})}
async function mock(page:Page,user=admin){await page.route('**/api/v1/auth/me',r=>json(r,{user}));await page.route('**/api/v1/auth/csrf',r=>json(r,{csrfToken:'csrf'}));await page.route('**/api/v1/taxonomy/bootstrap**',r=>json(r,taxonomy));await page.route('**/api/v1/assessments**',r=>{const u=new URL(r.request().url());if(r.request().method()==='GET'&&u.pathname==='/api/v1/assessments')return json(r,{items:[summary],page:1,limit:50,hasMore:false});if(r.request().method()==='GET')return json(r,{assessment:detail});return json(r,{assessment:detail})});await page.route('**/api/v1/questions**',r=>json(r,{items:[{id:'q-2',questionCode:'QDR-002',currentVersion:4,pathId:'path-1',subjectId:'subject-1',workflowStatus:'approved',type:'text',text:'إذا كان س + 2 = 5 فما قيمة س؟',imageAssetId:'',difficulty:'easy'}],page:1,limit:50,hasMore:false}))}
test('assessment center desktop and builder use bounded version-pinned questions',async({page})=>{await mock(page);await page.setViewportSize({width:1440,height:1000});await page.goto('/admin-dashboard/assessments');await expect(page.getByRole('heading',{name:'مركز الاختبارات'})).toBeVisible();await expect(page.getByText('محاكي القدرات الكمي')).toBeVisible();await page.getByRole('button',{name:'فتح / تعديل'}).click();await expect(page.getByRole('heading',{name:'تعديل الاختبار'})).toBeVisible();await expect(page.getByText('QDR-002')).toBeVisible();await page.getByText('QDR-002').click();await expect(page.getByText('v4')).toBeVisible();await page.screenshot({path:'test-results/assessment-desktop.png',fullPage:true})});
test('assessment center mobile keeps create and search reachable',async({page})=>{await mock(page);await page.setViewportSize({width:390,height:844});await page.goto('/admin-dashboard/assessments');await page.getByRole('button',{name:'اختبار جديد'}).click();await expect(page.getByRole('heading',{name:'إنشاء اختبار جديد'})).toBeVisible();await expect(page.getByLabel('بحث بنك الأسئلة')).toBeVisible();await page.screenshot({path:'test-results/assessment-mobile.png',fullPage:true})});
test('teacher never issues broad assessment list before exact taxonomy scope',async({page})=>{let lists=0;await mock(page,teacher);await page.route('**/api/v1/assessments**',r=>{const u=new URL(r.request().url());if(r.request().method()==='GET'&&u.pathname==='/api/v1/assessments'){lists++;return json(r,{items:[summary],page:1,limit:50,hasMore:false})}return json(r,{assessment:detail})});await page.goto('/admin-dashboard/assessments');await expect(page.getByText(/اختر المسار ثم المادة/)).toBeVisible();expect(lists).toBe(0);await page.getByLabel('المسار').selectOption('path-1');await page.getByLabel('المادة').selectOption('subject-1');await expect(page.getByText('محاكي القدرات الكمي')).toBeVisible();expect(lists).toBe(1)});
