import{Bell,Loader2,RefreshCcw,Save,Send}from'lucide-react';
import{useEffect,useMemo,useState}from'react';
import{useAuth}from'../../auth/state/AuthProvider';
import{notificationClient}from'../api/notification-client';
import type{NotificationChannel,NotificationDelivery,NotificationTemplate}from'../api/notification-types';

const roles=[['student','طالب'],['parent','ولي أمر'],['teacher','معلم'],['supervisor','مشرف'],['school_admin','إدارة مدرسة'],['admin','مدير منصة']] as const;
const channels:[NotificationChannel,string][]=[['in_app','داخل المنصة'],['email','البريد'],['whatsapp','واتساب']];

export function NotificationsAdminPage(){
 const{user,loading:authLoading,getCsrfToken}=useAuth();
 const[templates,setTemplates]=useState<NotificationTemplate[]>([]);
 const[deliveries,setDeliveries]=useState<NotificationDelivery[]>([]);
 const[busy,setBusy]=useState(true);const[saving,setSaving]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[reload,setReload]=useState(0);

 const[key,setKey]=useState('');const[name,setName]=useState('');const[templateChannel,setTemplateChannel]=useState<NotificationChannel>('in_app');const[templateSubject,setTemplateSubject]=useState('');const[templateTitle,setTemplateTitle]=useState('');const[templateBody,setTemplateBody]=useState('');const[variables,setVariables]=useState('');const[revision,setRevision]=useState(0);
 const[templateKey,setTemplateKey]=useState('');const[title,setTitle]=useState('');const[subject,setSubject]=useState('');const[body,setBody]=useState('');const[selectedChannels,setSelectedChannels]=useState<NotificationChannel[]>(['in_app']);const[selectedRoles,setSelectedRoles]=useState<string[]>([]);const[userIds,setUserIds]=useState('');const[variableJSON,setVariableJSON]=useState('{}');

 useEffect(()=>{if(authLoading||!user||!user.roles.includes('admin'))return;const c=new AbortController();setBusy(true);setError('');
  Promise.all([notificationClient.templates(1,50,c.signal),notificationClient.deliveries(1,50,undefined,undefined,c.signal)]).then(([t,d])=>{setTemplates(t.items);setDeliveries(d.items)}).catch(e=>{if(!c.signal.aborted)setError(e instanceof Error?e.message:'تعذر تحميل مركز الإشعارات')}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()
 },[authLoading,reload,user]);

 const summary=useMemo(()=>({sent:deliveries.filter(x=>x.status==='sent').length,pending:deliveries.filter(x=>x.status==='pending'||x.status==='retrying').length,failed:deliveries.filter(x=>x.status==='failed').length}),[deliveries]);

 function editTemplate(row:NotificationTemplate){setKey(row.key);setName(row.name);setTemplateChannel(row.channel);setTemplateSubject(row.subject);setTemplateTitle(row.title);setTemplateBody(row.body);setVariables(row.variables.join(', '));setRevision(row.revision)}
 async function saveTemplate(){
  setSaving('template');setError('');setNotice('');
  try{const csrf=await getCsrfToken();await notificationClient.upsertTemplate({key:key.trim(),name:name.trim(),channel:templateChannel,subject:templateSubject.trim(),title:templateTitle.trim(),body:templateBody.trim(),variables:variables.split(',').map(x=>x.trim()).filter(Boolean),isActive:true,expectedRevision:revision},csrf);setNotice('تم حفظ القالب مع نسخة متفائلة قابلة للتدقيق.');setKey('');setName('');setTemplateSubject('');setTemplateTitle('');setTemplateBody('');setVariables('');setRevision(0);setReload(x=>x+1)}
  catch(e){setError(e instanceof Error?e.message:'تعذر حفظ القالب')}finally{setSaving('')}
 }
 function applyTemplate(row:NotificationTemplate){setTemplateKey(row.key);setTitle(row.title);setSubject(row.subject);setBody(row.body);setSelectedChannels([row.channel])}
 function toggleChannel(channel:NotificationChannel){setSelectedChannels(rows=>rows.includes(channel)?(rows.length===1?rows:rows.filter(x=>x!==channel)):[...rows,channel])}
 function toggleRole(role:string){setSelectedRoles(rows=>rows.includes(role)?rows.filter(x=>x!==role):[...rows,role])}
 async function sendCampaign(){
  let parsed:Record<string,string|number|boolean|null>={};try{parsed=JSON.parse(variableJSON||'{}')}catch{setError('صيغة متغيرات JSON غير صحيحة.');return}
  const ids=userIds.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean);if(!ids.length&&!selectedRoles.length){setError('حدد مستخدمين أو أدوار قبل الإرسال.');return}
  setSaving('campaign');setError('');setNotice('');
  try{const csrf=await getCsrfToken();const result=await notificationClient.send({templateKey:templateKey.trim(),title:title.trim(),subject:subject.trim(),body:body.trim(),channels:selectedChannels,userIds:ids,roles:selectedRoles,variables:parsed},csrf);setNotice(`تم إنشاء الحملة لـ ${result.campaign.recipients} مستلم و${result.campaign.created} سجل تسليم.`);setReload(x=>x+1)}
  catch(e){setError(e instanceof Error?e.message:'تعذر إنشاء الحملة')}finally{setSaving('')}
 }

 if(authLoading||busy)return <main dir="rtl" className="p-10 text-center font-black">جاري تحميل مركز الإشعارات...</main>;
 if(!user||!user.roles.includes('admin'))return <main dir="rtl" className="p-10 text-center font-black text-rose-700">هذه الشاشة لمدير المنصة فقط.</main>;

 return <main dir="rtl" className="mx-auto max-w-7xl space-y-5">
  <header className="rounded-3xl bg-slate-950 p-5 text-white sm:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-indigo-300"><Bell size={18}/><span className="text-xs font-black">COMMUNICATION / NOTIFICATIONS</span></div><h1 className="mt-2 text-2xl font-black">مركز الإشعارات</h1><p className="mt-2 text-sm leading-7 text-slate-300">قوالب وحملات وسجل تسليم موحد. الإرسال الخارجي يعالج في Worker ولا يتم داخل طلب HTTP.</p></div><button type="button" onClick={()=>setReload(x=>x+1)} className="inline-flex self-start items-center gap-2 rounded-xl border border-white/20 px-3 py-2 text-sm font-black"><RefreshCcw size={15}/>تحديث</button></div></header>
  {error?<div role="alert" className="rounded-xl bg-rose-50 p-3 font-bold text-rose-700">{error}</div>:null}{notice?<div className="rounded-xl bg-emerald-50 p-3 font-bold text-emerald-700">{notice}</div>:null}
  <section className="grid grid-cols-3 gap-3">{[['مُرسلة',summary.sent],['معلقة/إعادة',summary.pending],['فاشلة',summary.failed]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-4 text-center shadow-sm"><div className="text-2xl font-black">{value}</div><div className="mt-1 text-xs font-bold text-gray-500">{label}</div></div>)}</section>

  <section className="grid gap-5 xl:grid-cols-2">
   <div className="space-y-4 rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">قالب إشعار</h2><div className="grid gap-3 sm:grid-cols-2"><input aria-label="مفتاح القالب" value={key} onChange={e=>setKey(e.target.value)} placeholder="exam.reminder" className="rounded-xl border p-2.5"/><input aria-label="اسم القالب" value={name} onChange={e=>setName(e.target.value)} placeholder="تذكير اختبار" className="rounded-xl border p-2.5"/><select aria-label="قناة القالب" value={templateChannel} onChange={e=>setTemplateChannel(e.target.value as NotificationChannel)} className="rounded-xl border p-2.5">{channels.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><input aria-label="موضوع القالب" value={templateSubject} onChange={e=>setTemplateSubject(e.target.value)} placeholder="الموضوع" className="rounded-xl border p-2.5"/><input aria-label="عنوان القالب" value={templateTitle} onChange={e=>setTemplateTitle(e.target.value)} placeholder="العنوان" className="rounded-xl border p-2.5 sm:col-span-2"/><textarea aria-label="محتوى القالب" value={templateBody} onChange={e=>setTemplateBody(e.target.value)} placeholder="مرحبًا {{name}}" rows={4} className="rounded-xl border p-2.5 sm:col-span-2"/><input aria-label="متغيرات القالب" value={variables} onChange={e=>setVariables(e.target.value)} placeholder="name, score" className="rounded-xl border p-2.5 sm:col-span-2"/></div><button type="button" onClick={()=>void saveTemplate()} disabled={saving==='template'} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 font-black text-white disabled:opacity-40">{saving==='template'?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}حفظ القالب</button><div className="flex flex-wrap gap-2">{templates.map(row=><button key={row.id} type="button" onClick={()=>editTemplate(row)} className="rounded-xl border bg-gray-50 px-3 py-2 text-xs font-black">{row.name} · r{row.revision}</button>)}</div></div>

   <div className="space-y-4 rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">حملة جديدة</h2><select aria-label="قالب الحملة" value={templateKey} onChange={e=>{const value=e.target.value;setTemplateKey(value);const row=templates.find(x=>x.key===value);if(row)applyTemplate(row)}} className="w-full rounded-xl border p-2.5"><option value="">بدون قالب</option>{templates.filter(x=>x.isActive).map(row=><option key={row.id} value={row.key}>{row.name}</option>)}</select><input aria-label="عنوان الحملة" value={title} onChange={e=>setTitle(e.target.value)} placeholder="العنوان" className="w-full rounded-xl border p-2.5"/><input aria-label="موضوع الحملة" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="موضوع البريد (اختياري)" className="w-full rounded-xl border p-2.5"/><textarea aria-label="محتوى الحملة" value={body} onChange={e=>setBody(e.target.value)} rows={4} placeholder="المحتوى" className="w-full rounded-xl border p-2.5"/><div><div className="mb-2 text-xs font-black">القنوات</div><div className="flex flex-wrap gap-2">{channels.map(([id,label])=><button key={id} type="button" onClick={()=>toggleChannel(id)} className={`rounded-xl border px-3 py-2 text-xs font-black ${selectedChannels.includes(id)?'border-indigo-600 bg-indigo-50 text-indigo-800':'bg-white'}`}>{label}</button>)}</div></div><div><div className="mb-2 text-xs font-black">الأدوار</div><div className="flex flex-wrap gap-2">{roles.map(([id,label])=><button key={id} type="button" onClick={()=>toggleRole(id)} className={`rounded-xl border px-3 py-2 text-xs font-black ${selectedRoles.includes(id)?'border-emerald-600 bg-emerald-50 text-emerald-800':'bg-white'}`}>{label}</button>)}</div></div><textarea aria-label="معرفات المستخدمين" value={userIds} onChange={e=>setUserIds(e.target.value)} rows={2} placeholder="UUIDs اختيارية، مفصولة بفاصلة أو مسافة" className="w-full rounded-xl border p-2.5"/><textarea aria-label="متغيرات الحملة" value={variableJSON} onChange={e=>setVariableJSON(e.target.value)} rows={2} className="w-full rounded-xl border p-2.5 font-mono text-xs"/><p className="text-xs font-bold leading-6 text-gray-500">الحد الصارم 10,000 مستلم للحملة: يتم عدّ الجمهور كاملًا أولًا ثم قراءته keyset على دفعات 500؛ أي جمهور أكبر يفشل مغلقًا بدون truncation. البريد وواتساب ينشئان سجلات pending ويعالجهما Worker بإعادة محاولة محدودة؛ لا يتم ادعاء إرسال مزود غير مهيأ.</p><button type="button" onClick={()=>void sendCampaign()} disabled={saving==='campaign'} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 font-black text-white disabled:opacity-40">{saving==='campaign'?<Loader2 size={16} className="animate-spin"/>:<Send size={16}/>}إنشاء الحملة</button></div>
  </section>

  <section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="border-b p-4"><h2 className="font-black">سجل التسليم</h2></div>{deliveries.length===0?<div className="p-8 text-center text-sm font-bold text-gray-500">لا توجد سجلات تسليم.</div>:<div className="divide-y">{deliveries.map(row=><article key={row.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="font-black text-gray-900">{row.title}</div><div className="mt-1 text-xs font-bold text-gray-500">{row.channel} · {row.recipientUserId||'مستخدم محذوف'} · retry {row.retryCount}</div>{row.failureReason?<div className="mt-1 text-xs font-bold text-rose-600">{row.failureReason}</div>:null}</div><span className="rounded-xl border px-3 py-2 text-xs font-black">{row.status}</span></article>)}</div>}</section>
 </main>;
}
